name: pixiv_live_proxy_server
description: 免代理Pixiv Live
version: 0.0.2
homepage: https://pixiv.xiaocao.moe/#/pixiv-live-proxy-server/dart
repository: https://github.com/git-xiaocao/pixiv_live_proxy_server

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dio: ^5.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
